format = """
[](#3B4252)\
$username\
[](bg:#434C5E fg:#3B4252)\
$directory\
[](fg:#434C5E bg:#4C566A)\
$git_branch\
$git_status\
$git_state\
[](fg:#4C566A bg:#86BBD8)\
[$c\
$dart\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$python](fg:#292e42 bg:#86BBD8 bold)\
[](fg:#86BBD8 bg:#06969A)\
$docker_context\
[](fg:#06969A bg:#33658A)\
$cmd_duration\
$localip\
[ ](fg:#33658A)\
"""
command_timeout = 5000
# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "bg:#3B4252"
style_root = "bg:#3B4252"
format = '[$user ]($style)'

[directory]
style = "bg:#434C5E"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

version_color = "fg:#292e42 bg:#86BBD8 bold"

[c]
symbol = " "
format = ' $symbol ($version) '

[cmd_duration]
style = "bg:#33658A"
format = '[ took $duration ]($style)'

[dart]
symbol = " "
format = ' $symbol ($version) '

[docker_context]
symbol = " "
style = "bg:#06969A"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
format = ' $symbol ($version) '

[elm]
symbol = " "
format = ' $symbol ($version) '

[git_branch]
symbol = ""
style = "bg:#4C566A"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#4C566A"
format = '[$all_status$ahead_behind ]($style)'

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '

[golang]
symbol = " "
format = ' $symbol ($version) '

[haskell]
symbol = " "
format = ' $symbol ($version) '

[java]
symbol = " "
format = ' $symbol ($version) '

[julia]
symbol = " "
format = ' $symbol ($version) '

[nodejs]
symbol = " "
format = ' $symbol ($version) '

[nim]
symbol = " "
format = ' $symbol ($version) '

[python]
symbol = " "
format = ' $symbol ($version) (\($virtualenv)\) '
python_binary = [
  "./venv/bin/python",
  "./.venv/bin/python",
  "python",
  "python3",
  "python2",
]
# python_binary = ['./venv/bin/python', 'python', 'python3', 'python2']

[rust]
symbol = ""
format = ' $symbol ($version) '

# [time]
# disabled = false
# use_12hr = true
# style = "bg:#33658A"
# format = '[ $time ]($style)'
